trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
